---
Name: shortcodable
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'sheadawson/silverstripe-shortcodable:javascript/editor_plugin.js'
    - 'sheadawson/silverstripe-shortcodable:javascript/shortcodable.js'
  extra_requirements_css:
    - 'sheadawson/silverstripe-shortcodable:css/shortcodable.css'
SilverStripe\Control\Director:
  rules:
    ShortcodableController: Silverstripe\Shortcodable\Controller\ShortcodableController
Silverstripe\Shortcodable\Shortcodable:
  htmleditor_names:
    - cms
Silverstripe\Shortcodable\HtmlEditorField:
  extensions:
    - Silverstripe\Shortcodable\Extensions\ShortcodableHtmlEditorField
SilverStripe\View\Parsers\ShortcodeParser:
  extensions:
    - Silverstripe\Shortcodable\Extensions\ShortcodableShortcodeParserExtension
