---
Name: shortcodable
After:
    - 'framework/*'
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'showpro/silverstripe-shortcodable: client/css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Silverstripe\Shortcodable\Controller\ShortcodableController

Silverstripe\Shortcodable\Shortcodable:
  htmleditor_names:
    - cms

HtmlEditorField:
  extensions:
    - Silverstripe\Shortcodable\Extensions\ShortcodableHtmlEditorField

Silverstripe\Shortcodable\ShortcodeParser:
  extensions:
    - Silverstripe\Shortcodable\Extensions\ShortcodableShortcodeParserExtension

SilverStripe\Admin\ModalController:
  extensions:
    - Silverstripe\Shortcodable\Extensions\ShortCodeModalExtension
